# Generated by Django 5.2.1 on 2025-05-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='paid_at',
        ),
    ]
