# Generated by Django 5.2.1 on 2025-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_date_payment_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpaymentstatus',
            name='total_price',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('DO', 'DO'), ('Invoice', 'Invoice'), ('Wallet', 'Wallet (Wish, OMT, ETC...)'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
    ]
