# Generated by Django 5.2.1 on 2025-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helparticle',
            old_name='is_visible',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='helpcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
