# Generated by Django 5.2.1 on 2025-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_unique_non_null_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='customers/avatar.png', null=True, upload_to='customers'),
        ),
    ]
