# Generated by Django 5.2.1 on 2025-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(default='Additional Phone', max_length=255),
        ),
    ]