# Generated by Django 5.2.1 on 2025-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlighted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('LBP', 'LBP'), ('USD', 'USD')], default='LBP', max_length=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('is_project_manager', models.BooleanField(default=False)),
                ('subtask_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('vat_value', models.PositiveIntegerField(default=11)),
                ('currency', models.CharField(choices=[('LBP', 'LBP'), ('USD', 'USD')], default='USD', max_length=5)),
                ('job_is_zero', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('closed_undelivered', 'Closed Undelivered'), ('completed', 'Completed')], default='created', max_length=20)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='projects_files')),
                ('frontdesk_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('LBP', 'LBP'), ('USD', 'USD')], default='USD', max_length=5)),
                ('task_priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('paid_status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid'), ('O', 'Overpaid')], default='U', max_length=1)),
                ('payment_method', models.CharField(choices=[('onAccount', 'On Account'), ('cash', 'Cash')], default='cash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_due_date', models.DateField(blank=True, null=True)),
                ('quote_validity', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_quote', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Taxname', max_length=200)),
                ('value', models.PositiveIntegerField(default=11, unique=True)),
            ],
            options={
                'verbose_name_plural': 'VAT',
            },
        ),
    ]
