# Generated by Django 5.2.1 on 2025-05-13 10:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_manager',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='managed_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
