# Generated by Django 5.2.1 on 2025-05-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_subtask_cancel_requested_subtask_is_canceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='vat_value',
        ),
        migrations.AddField(
            model_name='subtask',
            name='vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.vat'),
        ),
    ]
