# Generated by Django 5.2.1 on 2025-05-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_subtask_vat_value_subtask_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='notes',
            field=models.TextField(),
        ),
    ]
