# Generated by Django 5.2.1 on 2025-05-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_subtask_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('done', 'All Subtasks Done'), ('paid', 'Paid'), ('closed', 'Closed'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tasks.task'),
        ),
    ]
