# Generated by Django 5.2.1 on 2025-05-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status_alter_taskactivitylog_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_manager',
            new_name='user',
        ),
    ]
