# Generated by Django 5.2.1 on 2025-05-17 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_project_manager_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_delivered',
        ),
        migrations.CreateModel(
            name='DeliveredTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_person', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to=settings.AUTH_USER_MODEL)),
                ('main_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ['-delivery_date'],
            },
        ),
    ]
