# Generated by Django 5.2.1 on 2025-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_delivered_at_remove_task_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
