# Generated by Django 5.2.1 on 2025-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_subtask_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='update',
            new_name='is_updated',
        ),
    ]
