# Generated by Django 5.2.1 on 2025-05-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_update_subtask_is_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='notes',
            new_name='notes_from_top',
        ),
    ]
