# Generated by Django 5.2.1 on 2025-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_notes_subtask_notes_from_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='notes_from_operator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
