# Generated by Django 5.2.1 on 2025-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_subtask_notes_from_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_highlighted',
            field=models.BooleanField(default=True),
        ),
    ]
