# Generated by Django 5.2.1 on 2025-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_notification_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveredtask',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
