# Generated by Django 5.2.1 on 2025-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_deliveredtask_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredtask',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
