# Generated by Django 5.2.1 on 2025-05-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_deliveredtask_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredtask',
            name='main_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
