# Generated by Django 5.2.1 on 2025-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_deliveredtask_main_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('done', 'All Subtasks Done'), ('closed', 'Closed'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskname',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
