# Generated by Django 5.2.1 on 2025-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_task_status_alter_taskname_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('done', 'All Subtasks Done'), ('closed', 'Closed'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], db_index=True, default='created', max_length=20),
        ),
    ]
