# Generated by Django 5.2.1 on 2025-06-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0018_alter_mailbox_imap_port'),
        ('tasks', '0025_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='cancel_subtask_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='custom_email.email'),
        ),
        migrations.AddField(
            model_name='task',
            name='from_email',
            field=models.BooleanField(default=False),
        ),
    ]
