# Generated by Django 5.2.1 on 2025-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_subtask_cancel_subtask_reason_task_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(choices=[('DO', 'DO'), ('Invoice', 'Invoice'), ('Wallet', 'Wallet'), ('onAccount', 'On Account'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
    ]