# Generated by Django 5.2.1 on 2025-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_task_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(choices=[('DO', 'DO'), ('Invoice', 'Invoice'), ('Wallet', 'Wallet (Wish, OMT, ETC...)'), ('onAccount', 'On Account'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
    ]
