# Generated by Django 5.2.1 on 2025-06-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_task_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactivitylog',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='task',
            name='final_location',
            field=models.CharField(blank=True, choices=[('FRONT DESK', 'FRONT DESK'), ('OPERATOR DESK', 'OPERATOR DESK'), ('BEHIND KHALED', 'BEHIND KHALED')], help_text='Predefined location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='other_location',
            field=models.CharField(blank=True, help_text='Custom location (used only if final_location is not selected)', max_length=100, null=True),
        ),
    ]
