# Generated by Django 5.2.1 on 2025-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_taskactivitylog_options_task_final_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('LBP', 'LBP'), ('USD', 'USD')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(choices=[('DO', 'DO'), ('Invoice', 'Invoice'), ('Wallet', 'Wallet (Wish, OMT, ETC...)'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
    ]
