# Generated by Django 5.2.1 on 2025-06-23 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0018_alter_mailbox_imap_port'),
        ('customers', '0006_alter_phone_name'),
        ('tasks', '0030_alter_project_balance_alter_project_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'is_done'], name='tasks_subta_task_id_71ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['user', 'is_done'], name='tasks_subta_user_id_1298ad_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['created_at'], name='tasks_subta_created_25bb0c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['paid_status'], name='tasks_task_paid_st_24783e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['order_number'], name='tasks_task_order_n_f3ff87_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['customer_name', 'status'], name='tasks_task_custome_602f98_idx'),
        ),
    ]
