# Generated by Django 5.2.1 on 2025-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_branch_task_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
