# Generated by Django 5.2.1 on 2025-05-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('outbox', 'Outbox')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='mailbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_email.mailbox'),
            preserve_default=False,
        ),
    ]
