# Generated by Django 5.2.1 on 2025-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0004_fetchstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
