# Generated by Django 5.2.1 on 2025-05-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0005_alter_email_message_id_alter_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='imap_host',
            field=models.CharField(default='mail.bookstop.co', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_host',
            field=models.CharField(default='mail.bookstop.co', max_length=255),
        ),
    ]
