# Generated by Django 5.2.1 on 2025-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0006_alter_mailbox_imap_host_alter_mailbox_smtp_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
