# Generated by Django 5.2.1 on 2025-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0007_email_has_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=512),
        ),
    ]
