# Generated by Django 5.2.1 on 2025-05-30 07:51

import custom_email.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0008_alter_email_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=custom_email.models.mailbox_attachment_path),
        ),
    ]
