# Generated by Django 5.2.1 on 2025-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0009_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='uid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
