# Generated by Django 5.2.1 on 2025-05-31 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0011_auto_20250531_0827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['mailbox', 'folder', 'date_received'], name='custom_emai_mailbox_f161ad_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['mailbox', 'folder'], name='custom_emai_mailbox_710540_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['subject'], name='custom_emai_subject_998486_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sender'], name='custom_emai_sender_a04571_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['message_id'], name='custom_emai_message_45c612_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['uid'], name='custom_emai_uid_b036d2_idx'),
        ),
    ]
