# Generated by Django 5.2.1 on 2025-05-31 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0012_email_custom_emai_mailbox_f161ad_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['mailbox', 'folder', 'is_read', 'date_received'], name='custom_emai_mailbox_7b7f22_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['mailbox', 'folder', 'status', 'date_received'], name='custom_emai_mailbox_dce357_idx'),
        ),
    ]
