# Generated by Django 5.2.1 on 2025-05-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0013_email_custom_emai_mailbox_7b7f22_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['email', 'filename'], name='custom_emai_email_i_b08eae_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['filename'], name='custom_emai_filenam_2ad97f_idx'),
        ),
    ]
