# Generated by Django 5.2.1 on 2025-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0016_remove_useremailaccount_user_useremailaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=2024),
        ),
    ]
