# Generated by Django 5.2.1 on 2025-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_email', '0017_alter_email_message_id_alter_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='imap_port',
            field=models.PositiveIntegerField(default=143),
        ),
    ]
